import React, { useState, useEffect } from 'react';
import { NextPageContext } from 'next';
import Layout from '../components/Layout';
import ConceptCard from '../components/ConceptCard';

interface SsrVsCsrProps {
  serverTime: string;
}

/**
 * LAYMAN EXPLANATION:
 * This page shows the difference between code running on your computer (Browser) 
 * and code running on Vercel's computers (Server).
 */
const SsrVsCsr = ({ serverTime }: SsrVsCsrProps) => {
  const [clientTime, setClientTime] = useState<string>('Loading...');

  useEffect(() => {
    // This code ONLY runs in your browser after the page loads.
    setClientTime(new Date().toLocaleTimeString());
    
    const timer = setInterval(() => {
      setClientTime(new Date().toLocaleTimeString());
    }, 1000);

    return () => clearInterval(timer);
  }, []);

  return (
    <Layout title="SSR vs CSR | Demo">
      <h1>Server vs Client</h1>
      <p className="subtitle">Understanding where your code actually executes.</p>

      <div className="comparison glass">
        <div className="side">
          <h3>🖥️ Server-Side (SSR)</h3>
          <p>This time was generated on the server before the page even reached you.</p>
          <div className="time server">{serverTime}</div>
          <span className="note">Static until you refresh the page.</span>
        </div>

        <div className="divider"></div>

        <div className="side">
          <h3>💻 Client-Side (CSR)</h3>
          <p>This time is being generated by your own browser right now.</p>
          <div className="time client">{clientTime}</div>
          <span className="note">Updating every second via JavaScript.</span>
        </div>
      </div>

      <div className="grid">
        <ConceptCard 
          tag="Server"
          title="getInitialProps"
          description="Runs on the server for the first load. The visitor gets the final HTML immediately, which is incredibly fast and search-engine friendly."
        />
        <ConceptCard 
          tag="Client"
          title="useEffect"
          description="Runs after the page is 'hydrated' (React starts running in the browser). Use this for timers, animations, or data that doesn't need to be indexed by Google."
        />
        <ConceptCard 
          tag="Lesson"
          title="Hydration"
          description="The process where Next.js takes the static HTML from the server and 'attaches' React logic to it so it becomes interactive."
        />
      </div>

      <style jsx>{`
        h1 { color: var(--primary); font-size: 3rem; }
        .subtitle { color: var(--text-muted); margin-bottom: 2rem; }

        .comparison {
          display: flex;
          padding: 3rem;
          margin-bottom: 3rem;
          gap: 2rem;
          align-items: center;
        }

        .side {
          flex: 1;
          text-align: center;
          display: flex;
          flex-direction: column;
          gap: 1rem;
        }

        .divider {
          width: 1px;
          height: 150px;
          background: var(--glass-border);
        }

        .time {
          font-size: 3rem;
          font-weight: 800;
          font-family: monospace;
        }

        .server { color: #f43f5e; }
        .client { color: #10b981; }

        .note {
          font-size: 0.8rem;
          color: var(--text-muted);
          font-style: italic;
        }

        .grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
          gap: 2rem;
        }

        @media (max-width: 768px) {
          .comparison { flex-direction: column; }
          .divider { width: 100%; height: 1px; }
        }
      `}</style>
    </Layout>
  );
};

/**
 * We use getInitialProps to get the time from the server.
 */
SsrVsCsr.getInitialProps = async (ctx: NextPageContext) => {
  const serverTime = new Date().toLocaleTimeString();
  return { serverTime };
};

export default SsrVsCsr;
